/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightlosingRouteImport } from './routes/weightlosing'
import { Route as LonglivetyRouteImport } from './routes/longlivety'
import { Route as IndexRouteImport } from './routes/index'

const WeightlosingRoute = WeightlosingRouteImport.update({
  id: '/weightlosing',
  path: '/weightlosing',
  getParentRoute: () => rootRouteImport,
} as any)
const LonglivetyRoute = LonglivetyRouteImport.update({
  id: '/longlivety',
  path: '/longlivety',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/longlivety': typeof LonglivetyRoute
  '/weightlosing': typeof WeightlosingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/longlivety': typeof LonglivetyRoute
  '/weightlosing': typeof WeightlosingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/longlivety': typeof LonglivetyRoute
  '/weightlosing': typeof WeightlosingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/longlivety' | '/weightlosing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/longlivety' | '/weightlosing'
  id: '__root__' | '/' | '/longlivety' | '/weightlosing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LonglivetyRoute: typeof LonglivetyRoute
  WeightlosingRoute: typeof WeightlosingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weightlosing': {
      id: '/weightlosing'
      path: '/weightlosing'
      fullPath: '/weightlosing'
      preLoaderRoute: typeof WeightlosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longlivety': {
      id: '/longlivety'
      path: '/longlivety'
      fullPath: '/longlivety'
      preLoaderRoute: typeof LonglivetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LonglivetyRoute: LonglivetyRoute,
  WeightlosingRoute: WeightlosingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
